use_frameworks!

platform :ios, '13.0'

target 'STAnalytics_Example' do
  pod 'STAnalytics', :path => '../'
#  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  # Firebase崩溃报告
#  pod'Firebase/Crashlytics'
  target 'STAnalytics_Tests' do
    inherit! :search_paths

    
  end
end
